ARG version
FROM almalinux:${version:-9}
ENV course="aws" \
    duration="120hrs"
ARG trainer="sivakumar"
RUN echo "hi coursen is: ${course}, duration is: ${duration}, tratiner is: ${trainer}"
CMD ["sleep", "1000"]    